Repository topjohnwu/Magisk, pull requests merged in 2023-03, with the labels that each got.

#6236 install.md: Mention Heimdall beside Odin
  docs/install.md
Labels: documentation

#6374 Update ota.md
  docs/ota.md
Labels: documentation

#6718 Support `untrusted_app_32`
  native/src/sepolicy/rules.cpp
Labels: Core

#6704 Do not always create new adapter
  app/src/main/java/com/topjohnwu/magisk/databinding/RvItemAdapter.kt
Labels: APP

#6705 Fix currentFocus
  app/src/main/java/com/topjohnwu/magisk/arch/NavigationActivity.kt
  app/src/main/java/com/topjohnwu/magisk/arch/UIActivity.kt
Labels: APP

#6742 Drop trailing garbage of gzip decompress
  native/src/boot/compress.cpp
Labels: Core

#6740 Fix unpack -n and repack -n of ZIMAGE kernel
  native/src/boot/bootimg.cpp
Labels: Core

#6761 Fix su log with long command
  app/src/main/res/layout/item_log_access_md2.xml
Labels: APP

#6748 Remove meaningless umount in magiskinit
  native/src/init/twostage.cpp
Labels: Core

#6730 Use RV to show Magisk logs
  app/src/main/java/com/topjohnwu/magisk/ui/log/LogRvItem.kt
  app/src/main/java/com/topjohnwu/magisk/ui/log/LogViewModel.kt
  app/src/main/java/com/topjohnwu/magisk/ui/log/SuLogRvItem.kt
  app/src/main/res/layout/fragment_log_md2.xml
  app/src/main/res/layout/include_log_magisk.xml
  app/src/main/res/layout/item_log_access_md2.xml
  app/src/main/res/layout/item_log_textview.xml
Labels: APP

#6739 Add amonet microloader support
  native/src/boot/bootimg.cpp
  native/src/boot/bootimg.hpp
  native/src/boot/format.hpp
Labels: Core

#6751 Refactor magiskrc
  native/src/core/bootstages.cpp
  native/src/core/daemon.cpp
  native/src/core/magisk.cpp
  native/src/include/daemon.hpp
  native/src/include/magisk.hpp
  native/src/init/magiskrc.inc
  native/src/init/rootdir.cpp
  native/src/sepolicy/rules.cpp
  scripts/avd_magisk.sh
Labels: Core
